# fly.toml app configuration file generated for inscription-indexer on 2024-01-22T16:24:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "inscription-indexer"
primary_region = "mad"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
